### ISSUE TITLE
Billiard support for Windows on python2.7

### ISSUE THREAD

**Issue by linar-jether** [celery/billiard#239]
What is the current status? is windows support completely dropped after version 3.5?

Currently when trying to create a Pool object the following error is raised (https://github.com/celery/billiard/issues/198): 
in `popen_spawn_win32.py:64`
```python
TypeError: argument 1 must be an integer, not _subprocess_handle
```

**Comment by sparrowt** [comment]
@auvipy you kindly mentioned in a few places (e.g. https://github.com/celery/celery/issues/3383#issuecomment-408927156 and https://github.com/celery/celery/issues/3655#issuecomment-358355723) that windows support is now returning / has returned, is that correct? That would be amazing if it is the case.

If so, this ticket is currently blocking support on python 2.7, are you planning on supporting celery / billiard only on python 3 on Windows?

(P.S. it seems even the official billiard tests are failing on windows python 2.7 due to this issue, see https://ci.appveyor.com/project/ask/billiard which currently points to [these](https://ci.appveyor.com/project/ask/billiard/build/job/esitp7n0mik4h2gi) [failures](https://ci.appveyor.com/project/ask/billiard/build/job/pk74ncry9lmoq4lk) which include this `TypeError`)

**Comment by thedrow** [comment]
Windows is not a priority for us but we do accept patches for it.

**Comment by okomarov** [comment]
I am wondering who is using windows (server) + python2.7. One use case that comes to mind are legacy system in banks...

**Comment by sparrowt** [comment]
Thank you @Jamim!

**Comment by zezobrandz301** [comment]
0557954095
